repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          - --max-line-length=127 # Example: Set max line length
          - --max-complexity=10 # Example: Set max complexity
        exclude: ^node_modules/ # Place the exclude key at the hook level
