name: Python CI/CD

on:
  push:
    branches:
      - master
      - scrapping-*
  pull_request:
    branches:
      - main
      - scrapping-*

jobs:
  # Primer trabajo: Instalar dependencias
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Check out el código
      - name: Check out code
        uses: actions/checkout@v2

      # Paso 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  # Segundo trabajo: Ejecutar pruebas unitarias
  run_tests:
    runs-on: ubuntu-latest
    needs: install_dependencies # Este trabajo depende de que el anterior se haya completado

    steps:
      # Paso 1: Check out el código
      - name: Check out code
        uses: actions/checkout@v2

      # Paso 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 4: Ejecutar las pruebas
      - name: Run tests
        run: |
          pytest

  # Tercer trabajo: Despliegue con Serverless (solo en ramas que empiezan con scrapping-)
  deploy:
    runs-on: ubuntu-latest
    needs: run_tests # Este trabajo depende de que las pruebas se hayan completado correctamente
    if: startsWith(github.ref, 'refs/heads/scrapping-') # Solo ejecuta este paso en ramas que comienzan con scrapping-

    steps:
      # Paso 1: Check out el código
      - name: Check out code
        uses: actions/checkout@v2

      # Paso 2: Configurar AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Paso 3: Instalar Serverless Framework y dependencias del package.json
      - name: Install Serverless and dev dependencies
        run: |
          npm install -g serverless
          npm install

      - name: Deploy with Serverless
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: serverless deploy
