name: Python CI/CD

on:
  push:
    branches:
      - master
      - scrapping-*
  pull_request:
    branches:
      - main
      - scrapping-*

jobs:
  # Primer trabajo: Instalar dependencias
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Check out el código
      - name: Check out code
        uses: actions/checkout@v2

      # Paso 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  # Segundo trabajo: Ejecutar pruebas unitarias
  run_tests:
    runs-on: ubuntu-latest
    needs: install_dependencies # Este trabajo depende de que el anterior se haya completado

    steps:
      # Paso 1: Check out el código
      - name: Check out code
        uses: actions/checkout@v2

      # Paso 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 4: Ejecutar las pruebas
      - name: Run tests
        run: |
          pytest
      # TODO: Se debe crear un paso donde haga deploy (solo en master y q se active manualmente) a prod
